name: Post Sticky Comment
description: Post a sticky comment
inputs:
  title:
    description: Unique title
    required: true
    type: string
  body:
    description: Body
    required: true
    type: string
  pr:
    description: Pull Request Number
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Create metadata
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          
          try {
            // Get inputs from the GitHub Action
            const title = JSON.parse(`"${{ inputs.title }}"`);  // Safely parsing as a string
            const body = JSON.parse(`"${{ inputs.body }}"`);    // Safely parsing as a string
            const pr = ${{ inputs.pr }};

            // Create the content of the JSON file
            const content = JSON.stringify({
              title: title,
              body: body,
              pr_number: pr
            }, null, 2);
            console.log(content)
          
            fs.writeFileSync('comment.json', content);
          
            console.log('comment.json file has been written successfully.');
          } catch (error) {
            core.setFailed(`Action failed with error: ${error}`);
          }

    - name: 📤 Upload data
      uses: actions/upload-artifact@v4
      with:
        name: comment_artifacts
        path: |
          comment.json
